name: mint
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pip
- pip:
  - dipy==1.7.0
  - fury==0.9.0
  - aenum==3.1.15
  - auto_mix_prep==0.2.0
  - chamferdist==1.0.3
  - cmasher==1.8.0
  - evals==3.0.1.post1
  - h5py==3.6.0
  - lightning==2.2.4
  - matplotlib==3.5.0
  - neuroCombat==0.2.12
  - nibabel==3.2.1
  - numpy==1.21.2
  - pandas==1.3.5
  - Pillow==8.4.0
  - Pillow==10.3.0
  - pytorch_lightning==2.2.4
  - PyYAML==6.0
  - PyYAML==6.0.1
  - scikit_learn==1.0.2
  - scipy==1.7.3
  - seaborn==0.11.2
  - statsmodels==0.13.0
  - torch==1.10.0
  - torchvision==0.11.1
